#DROP DATABASE APS_Ambiental;

CREATE DATABASE APS_Ambiental;

USE APS_Ambiental;

CREATE TABLE TIPOS(
	ID_TIPO int AUTO_INCREMENT NOT NULL,
	NOME_TABELA varchar(30) NOT NULL,
	CHAVE varchar(30) NOT NULL,
	VALOR varchar(30) NOT NULL,
	PRIMARY KEY (ID_TIPO ASC));


CREATE TABLE USUARIOS(
	ID_USUARIO int AUTO_INCREMENT NOT NULL,
	TIPO_USUARIO int NOT NULL,
	USUARIO varchar(50) NOT NULL,
	SENHA varchar(50) NOT NULL,
	NOME varchar(70) NOT NULL,
	CONSTRAINT ix_nome_usuario PRIMARY KEY (USUARIO ASC),
    KEY (ID_USUARIO)
    );


CREATE TABLE EMPRESAS(
	ID_EMPRESA int AUTO_INCREMENT NOT NULL,
	TIPO_EMPRESA int NOT NULL,
	RAZAO_SOCIAL varchar(70) NOT NULL,
	NOME_ABREVIADO varchar(30) NOT NULL,
	ENDERECO varchar(200) NOT NULL,
	CNPJ varchar(20) NOT NULL,
	CONSTRAINT ix_empresas PRIMARY KEY (RAZAO_SOCIAL ASC, CNPJ ASC),
    KEY (ID_EMPRESA)
    );


CREATE TABLE DESPEJOS(
	ID_DESPEJOS int AUTO_INCREMENT NOT NULL,
    TIPO_DESPEJO int NULL,
    EMPRESA int NOT NULL,
	REGIAO varchar(20) NOT NULL,
	DESCRICAO varchar(150) NOT NULL,
	QUANTIDADE int NULL,
	PRIMARY KEY (ID_DESPEJOS ASC));


ALTER TABLE USUARIOS ADD CONSTRAINT FK_TIPO_USUARIO FOREIGN KEY (TIPO_USUARIO) REFERENCES TIPOS (ID_TIPO);
#ALTER TABLE USUARIOS CHECK CONSTRAINT FK_TIPO_USUARIO;


ALTER TABLE EMPRESAS ADD CONSTRAINT FK_TIPO_EMPRESA FOREIGN KEY (TIPO_EMPRESA) REFERENCES TIPOS (ID_TIPO);
#ALTER TABLE EMPRESAS CHECK CONSTRAINT FK_TIPO_EMPRESA;


ALTER TABLE DESPEJOS ADD CONSTRAINT FK_TIPO_DESPEJO FOREIGN KEY (TIPO_DESPEJO) REFERENCES TIPOS (ID_TIPO);
#ALTER TABLE DESPEJOS CHECK CONSTRAINT FK_TIPO_DESPEJO;

INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "USUARIOS", "TIPO_USUARIO", "SECRETARIA");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "USUARIOS", "TIPO_USUARIO", "INSPETOR");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "EMPRESAS", "TIPO_EMPRESA", "GRANDE PORTE");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "EMPRESAS", "TIPO_EMPRESA", "MEDIO PORTE");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "EMPRESAS", "TIPO_EMPRESA", "PEQUENO PORTE");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "DESPEJOS", "TIPO_DESPEJO", "GRANDE");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "DESPEJOS", "TIPO_DESPEJO", "MEDIO");
INSERT INTO TIPOS(ID_TIPO, NOME_TABELA, CHAVE, VALOR) VALUES (null, "DESPEJOS", "TIPO_DESPEJO", "PEQUENO");

INSERT INTO USUARIOS(ID_USUARIO, TIPO_USUARIO, USUARIO, SENHA, NOME) VALUES (null, 1, "john.doe.inspect@gmail.com", "123456", "john doe inspect");
INSERT INTO USUARIOS(ID_USUARIO, TIPO_USUARIO, USUARIO, SENHA, NOME) VALUES (null, 2, "john.doe.secret@gmail.com", "123456", "john doe secret");

INSERT INTO EMPRESAS(ID_EMPRESA, TIPO_EMPRESA, RAZAO_SOCIAL, NOME_ABREVIADO, ENDERECO, CNPJ) VALUES (null, 3, "RAZAO1", "1", "ENDERECO1", "CNPJ1");
INSERT INTO EMPRESAS(ID_EMPRESA, TIPO_EMPRESA, RAZAO_SOCIAL, NOME_ABREVIADO, ENDERECO, CNPJ) VALUES (null, 4, "RAZAO2", "2", "ENDERECO2", "CNPJ2");
INSERT INTO EMPRESAS(ID_EMPRESA, TIPO_EMPRESA, RAZAO_SOCIAL, NOME_ABREVIADO, ENDERECO, CNPJ) VALUES (null, 5, "RAZAO3", "3", "ENDERECO3", "CNPJ3");

INSERT INTO DESPEJOS(ID_DESPEJOS, EMPRESA, TIPO_DESPEJO, REGIAO, DESCRICAO, QUANTIDADE) VALUES (null, 6, 1, "BARUERI", "LIXO DE PEQUENO PORTE LIBERADO EM BARUERI", 100);
INSERT INTO DESPEJOS(ID_DESPEJOS, EMPRESA, TIPO_DESPEJO, REGIAO, DESCRICAO, QUANTIDADE) VALUES (null, 7, 2, "OSASCO", "LIXO DE MEDIO PORTE LIBERADO EM OSASCO", 300);
INSERT INTO DESPEJOS(ID_DESPEJOS, EMPRESA, TIPO_DESPEJO, REGIAO, DESCRICAO, QUANTIDADE) VALUES (null, 8, 3, "JANDIRA", "LIXO DE GRANDE PORTE LIBERADO EM JANDIRA", 1000);

SELECT * FROM TIPOS;
SELECT * FROM USUARIOS;
SELECT * FROM EMPRESAS;
SELECT * FROM DESPEJOS;

SELECT * FROM USUARIOS WHERE USUARIO = 'john.doe.inspect@gmail.com';